global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'oltp-db'
    static_configs:
      - targets: ['oltp-db:5432']

  - job_name: 'nifi'
    static_configs:
      - targets: ['nifi:8181']

  - job_name: 'olap-db'
    static_configs:
      - targets: ['olap-db:5433']
